database_MYSQL_USERNAME: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35626437613434636365366537343830363261386135383434303133386165646434323132396333
          3966336437373264323166623764306436656162353936310a636435363361356437626531313165
          61653635333163353638326538306434316634653739376161353932343136633833323761633831
          3437623966383939350a343061356365306235353633666664623461333262343935366364653539
          3836
MYSQL_ROOT_PASSWORD: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37366330323132623734633936363963633239663139653564303330373430653031646463653838
          3838616133643234613030316163393632326130623033360a623836643333366535663436393235
          64333135336236613562333666653830373062316234656666623566353363373762616230646634
          6362366235386530320a323737336163366632646234326131356439663237316534333938386438
          3535

APP_KEY: 'base64:oPD/hrRXGvA1hydZp17JAQH2PnflMgp4P5OMWoldWTM='

docker_service_deploy_project_dir: '$HOME/docker_compose'

